name: CI

on:
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request:

jobs:

  install:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: [3.12]
        os: [ubuntu-latest]

    defaults:
      run:
        shell: bash -leo pipefail {0}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mamba setup
        uses: mamba-org/setup-micromamba@v3
        with:
          environment-file: environment.yml
          cache-downloads: false

      - name: Install dependencies
        run: |
          python --version
          python -m pip install -e .
          python -m pip freeze
